import Foundation

enum ContextManifest {

    /// Write a context file summarizing the canvas tiles to the worktree
    @MainActor static func write(canvas: PlanCanvasState) {
        let dir = (canvas.worktreePath as NSString).appendingPathComponent(".budahade")
        try? FileManager.default.createDirectory(
            atPath: dir, withIntermediateDirectories: true
        )

        var lines: [String] = [
            "<!-- Auto-generated by BudahADE -- do not edit -->",
            "# Planning Context",
            "",
        ]

        var images: [String] = []
        var documents: [String] = []
        var urls: [String] = []
        var agents: [String] = []

        for element in canvas.allTiles {
            guard case .tile(let tileType) = element.kind else { continue }
            switch tileType {
            case .image(let path):
                images.append(path)
            case .markdown(let path):
                documents.append(path)
            case .browser(let url):
                if let url { urls.append(url.absoluteString) }
            case .terminal(_, let agent):
                agents.append(agent.displayName)
            case .stickyNote, .textBox:
                break
            }
        }

        if !images.isEmpty {
            lines.append("## Reference Images")
            for path in images {
                lines.append("- `\(path)`")
            }
            lines.append("")
        }

        if !documents.isEmpty {
            lines.append("## Documents")
            for path in documents {
                lines.append("- `\(path)`")
            }
            lines.append("")
        }

        if !urls.isEmpty {
            lines.append("## Browser References")
            for url in urls {
                lines.append("- \(url)")
            }
            lines.append("")
        }

        if !agents.isEmpty {
            lines.append("## Active Conversations")
            for name in agents {
                lines.append("- \(name)")
            }
            lines.append("")
        }

        let content = lines.joined(separator: "\n")
        let path = (dir as NSString).appendingPathComponent("plan-context.md")
        try? content.write(toFile: path, atomically: true, encoding: .utf8)
    }
}
